### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by yixiang** [zhchang/pand#1]
Requesting for mac support.

First thing to fix on mac, replace wget with curl, as wget is not included on mac out of box.

```
        if call(['curl','-o','android-sdk_r24-linux.tgz','http://dl.google.com/android/android-sdk_r24-linux.tgz']) != 0:
```

**Comment by zhchang** [comment]
yeah, good catch.
will support mac using curl as well as use mac version of Android SDK instead.

**Comment by zhchang** [comment]
pand now supports both wget and curl.

**Comment by yixiang** [comment]
# with commit 90a53f5

So where should I install sdks?
/Users/yixiang
Command '['which', 'wget']' returned non-zero exit status 1

**Comment by yixiang** [comment]
actually, you've made things more complicated than necessary, curl is almost always included in a linux/unit distribution, you can assume it's availability. I suggest drop wget, and make the download code much simpler and cleaner.

**Comment by zhchang** [comment]
advice taken

**Comment by yixiang** [comment]
tried again, still couldn't make it through 'pand env'. testing required.

**Comment by zhchang** [comment]
yeah. finally got a chance to really run this on a mac machine. the pand env should be working now. ANT is pre-requisite for the rest of pand commands to work.

**Comment by zhchang** [comment]
fixed, closing issue
